export type ColorOption = { value: string; label: string };

/** 颜色（参考 ca/lexical/packages/lib 实现） */
export const colors: ColorOption[] = [
  { value: '', label: '默认颜色' },
  { value: '#f7acbc', label: '鸨色' },
  { value: '#ef5b9c', label: '踯躅色' },
  { value: '#f15b6c', label: '韩红' },
  { value: '#f69c9f', label: '红梅色' },
  { value: '#ca8687', label: '薄柿' },
  { value: '#d71345', label: '红色' },
  { value: '#aa363d', label: '银朱' },
  { value: '#f15a22', label: '金赤' },
  { value: '#da765b', label: '肉桂色' },
  { value: '#ae5039', label: '炼瓦色' },
  { value: '#8e3e1f', label: '栗色' },
  { value: '#ffc20e', label: '向日葵色' },
  { value: '#fdb933', label: '郁金色' },
  { value: '#ffd400', label: '蒲公英色' },
  { value: '#ffe600', label: '中黄' },
  { value: '#b2d235', label: '黄緑' },
  { value: '#a3cf62', label: '萌黄' },
  { value: '#78a355', label: '柳色' },
  { value: '#1d953f', label: '薄緑' },
  { value: '#225a1f', label: '草色' },
  { value: '#65c294', label: '若竹色' },
  { value: '#00ae9d', label: '青緑' },
  { value: '#7bbfea', label: '勿忘草色' },
  { value: '#33a3dc', label: '露草色' },
  { value: '#444693', label: '绀桔梗' },
  { value: '#494e8f', label: '绀蓝' },
  { value: '#fffffb', label: '白' },
  { value: '#f6f5ec', label: '生成色' },
  { value: '#d1c7b7', label: '石竹色' },
  { value: '#f2eada', label: '象牙色' },
  { value: '#d3d7d4', label: '乳白色' },
  { value: '#999d9c', label: '薄钝' },
  { value: '#74787c', label: '薄墨色' },
  { value: '#4f5555', label: '钝色' },
  { value: '#1d1626', label: '紫黒' },
];