export const editorTheme = {
  paragraph: 'mb-2 leading-relaxed',
  heading: {
    h1: 'text-3xl font-bold mt-4 mb-2',
    h2: 'text-2xl font-semibold mt-3 mb-2',
    h3: 'text-xl font-semibold mt-2 mb-1',
    h4: 'text-lg font-semibold mt-2 mb-1',
    h5: 'text-base font-semibold mt-2 mb-1',
    h6: 'text-sm font-semibold uppercase tracking-wide mt-2 mb-1',
  },
  quote: 'border-l-4 border-gray-300 pl-4 italic text-gray-600 my-2',
  list: {
    ul: 'list-disc pl-6 my-2',
    ol: 'list-decimal pl-6 my-2',
    listitem: 'my-0.5',
    nested: {
      listitem: 'list-none',
    },
    checklist: 'leditor-checklist',
    listitemChecked: 'leditor-checklist-item leditor-checklist-item-checked',
    listitemUnchecked: 'leditor-checklist-item',
  },
  text: {
    bold: 'font-bold',
    italic: 'italic',
    underline: 'underline',
    strikethrough: 'line-through',
    underlineStrikethrough: 'underline line-through',
    code: 'font-mono bg-gray-100 rounded px-1 py-0.5',
    subscript: 'align-sub text-xs',
    superscript: 'align-super text-xs',
    link: 'text-blue-600 underline cursor-pointer',
    alignLeft: 'text-left',
    alignCenter: 'text-center',
    alignRight: 'text-right',
    alignJustify: 'text-justify',
    indent: 'pl-6',
  },
  mark: 'bg-yellow-200/70 border-b-2 border-yellow-400 cursor-pointer',
  markOverlap: 'bg-orange-200/70 border-b-2 border-orange-400 cursor-pointer',
  code: 'block bg-gray-900 text-gray-100 p-3 rounded font-mono text-sm overflow-auto my-2',
  codeHighlight: {
    atrule: 'text-purple-300',
    attr: 'text-orange-300',
    boolean: 'text-yellow-300',
    builtin: 'text-sky-300',
    char: 'text-rose-300',
    class: 'text-sky-300',
    'class-name': 'text-sky-300',
    comment: 'text-gray-500 italic',
    constant: 'text-yellow-300',
    deleted: 'text-red-300 line-through',
    keyword: 'text-purple-300',
    number: 'text-amber-300',
    operator: 'text-pink-300',
    punctuation: 'text-gray-300',
    property: 'text-emerald-300',
    string: 'text-emerald-300',
    symbol: 'text-amber-300',
    tag: 'text-rose-300',
  },
  hr: 'border-t border-gray-300 my-4',
  image: 'max-w-full h-auto my-2 rounded',
  link: 'text-blue-600 underline cursor-pointer',
  table: 'border-collapse w-full my-2 table-fixed',
  tableRow: 'border border-gray-300',
  tableCell: 'border border-gray-300 p-1 align-top',
  tableCellHeader: 'border border-gray-300 p-1 bg-gray-100 font-semibold',
  tableCellSelected:
    'bg-blue-300/80 outline-2 outline-blue-500/80 outline -outline-offset-1',
};
